# Build step
FROM node:iron-alpine as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

# Final image
FROM nginx:latest
COPY --from=build /app/dist /var/site
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY fullchain3.pem /etc/nginx/fullchain.pem
COPY privkey3.pem /etc/nginx/privkey.pem
COPY options-ssl-nginx.conf /etc/nginx/options-ssl-nginx.conf
COPY ssl-dhparams.pem /etc/nginx/ssl-dhparams.pem

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
