# Build step
FROM node:18-alpine as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

# Final image
FROM nginx:latest
COPY --from=build /app/dist /var/site
COPY ./nginx.conf /etc/nginx/nginx.conf
CMD ["nginx","-g","daemon off;"]
