services:
  # Frontend
  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./dist/:/var/site/
      - /tmp/:/tmp/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    # command: "npm run dev"

  # Backend
  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ${PWD}:/app/
      - /tmp/:/tmp/
    ports:
      - 5000:5000
    environment:
      POSTGRES_PASSWORD: "password"
    # command: "flask --app src/backend/main.py run --debug --port 5000 --host 0.0.0.0"

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
      - /tmp/:/tmp/
    environment:
      POSTGRES_PASSWORD: "password"
      PGPASSWORD: "password"
      POSTGRES_DB: "annotations-db"
